"""
Django settings for hotel_site project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3nh7s_#y@$nqh#@1zo235rj94xtbmohbo=59axv2+auscklr&@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["http://myhotel-env.eba-ncgcrgyb.us-east-1.elasticbeanstalk.com/", "*"]

AUTH_USER_MODEL = 'reservations.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reservations.apps.ReservationsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hotel_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotel_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'reservations', 'static'),
]

MEDIA_URL = '/media/'

#Cognito service
COGNITO_USER_POOL_ID = "us-east-1_Vt8CLlYxo"
COGNITO_CLIENT_ID = "7cnjick3gp8ubsengut0s5tj0f"
COGNITO_CLIENT_SECRET = "1c13jvuinkasblh11sobp8vbhalgbre6be8oadep6ogmge3nbc70"
COGNITO_REGION = "us-east-1"

SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False

CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = False


#DynamoDB 
AWS_REGION = "us-east-1"
AWS_DYNAMODB_TABLE = "Rooms"
AWS_DYNAMODB_TABLE_1 = "Bookings"

# # #API GATEWAY
# # API_GATEWAY_BOOK_URL = "https://sodvr7qdxj.execute-api.us-east-1.amazonaws.com/prod/bookRoom"
# # API_GATEWAY_PAYMENT_URL = "https://jx36upcxz1.execute-api.us-east-1.amazonaws.com/prod/payment"

LAMBDA_BOOK_ROOM = "booking_handler"
LAMBDA_PAYMENT = "processPayment"

# #SNS
SNS_TOPIC_ARN = "arn:aws:sns:us-east-1:992382373831:PaymentNotifications"

#S3
AWS_S3_BUCKET_NAME = "myhotel-room-images"
AWS_S3_BASE_URL = f"https://{AWS_S3_BUCKET_NAME}.s3.{AWS_REGION}.amazonaws.com"

# hotel_site/settings.py
ROOM_SEARCH_API_URL = "https://abc123.execute-api.us-east-1.amazonaws.com/search"

GOOGLE_MAPS_API_KEY = "AIzaSyDSo9AZrzdzSgHYAaONUMLLRNWjkqATVR0"

GLUE_JOB_NAME = "hotel_report_job"

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}
