# Generated by Django 2.1.15 on 2025-11-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bed_size',
            field=models.CharField(blank=True, choices=[('King', 'King'), ('Queen', 'Queen'), ('Twin', 'Twin')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='layout',
            field=models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='occupancy',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Quad', 'Quad')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
