# Generated by Django 2.1.15 on 2025-11-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20251108_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
