# Generated by Django 2.1.15 on 2025-11-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20251109_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
