# Generated by Django 2.1.15 on 2025-11-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20251109_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
