# Generated by Django 2.1.15 on 2025-11-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20251109_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
