# Generated by Django 2.1.15 on 2025-11-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_roomimage_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
