# Generated by Django 2.1.15 on 2025-11-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20251109_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
